import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={styles.main}>
      <Sidebar />
      {children}
    </div>
  );
}
